from dataclasses import dataclass
from typing import Any, Optional


@dataclass(frozen=True)
class AssistantChatMessage:
    """
    Protocol defining the minimal interface for a message
    submitted to or generated by an AI assistant.
    """

    user_generated: bool
    """
    Whether the message was generated by the user (True)
    or by the AI assistant (False).
    """
    content: str
    """
    The content of the message.
    """
    metadata: Optional[dict[str, Any]] = None
    """
    Optional metadata associated with the message.
    """


@dataclass(frozen=True)
class AssistantChat:
    """
    Protocol defining the minimal interface for a chat exchanged between
    a user or system and an AI assistant.
    """

    messages: list[AssistantChatMessage]
    """
    The list of messages exchanged in the chat.
    """
    metadata: Optional[dict[str, Any]] = None
    """
    Optional metadata associated with the chat.
    """
