"""
Interoperability API between AI assistants and the
Alchemy platform.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Optional

from pydantic import BaseModel

from .i_assistant_chat import AssistantChat


@dataclass(frozen=True)
class AssistantSpecifications:
    """
    Protocol defining the minimal interface for an AI assistant
    specification.
    """

    name: str
    """
    The name of the assistant.
    """
    version: str
    """
    The version of the assistant.
    """
    chat_model_name: str
    """
    The name of the LLM used by the assistant.
    """


@dataclass(frozen=True)
class AssistantResponse:
    """
    The assistant response to a request, including the
    contextual input and output data used/generated
    during the request processing.
    """

    response: str
    """
    The assistant response to the request.
    """
    contextual_input_data: Optional[dict]
    """
    Additional information used by the assistant to respond
    to the request.
    """
    contextual_output_data: Optional[dict]
    """
    Additional information generated by the assistant when
    responding to the request.
    """


class Assistant(ABC):
    """
    Protocol defining the minimal interface an AI assistant must
    implement in order to be used within the Platform.

    An AI assistant relies on a knowledge model to process requests
    and provide answers.
    The model is based on Pydantic BaseModel, allowing for
    structured data handling and validation.
    """

    @property
    @abstractmethod
    def specifications(self) -> AssistantSpecifications:
        """
        :return: The assistant specifications.
        """

    @property
    @abstractmethod
    async def get_model(self) -> BaseModel:
        """
        :return: The current assistant knowledge model.
        """

    @abstractmethod
    async def invoke(
        self,
        request: str | AssistantChat,
        contextual_data: Optional[dict],
    ) -> AssistantResponse:
        """
        Invoke the assistant on the provided request.

        :param request: The request to process, either as a
            simple string or as the full chat history including the request.
        :param contextual_data: Additional information to be used when processing
            the request (e.g., user profile information, system state, etc.).
            The assistant can choose to ignore this data if not relevant for the
            request processing.
        :return: The assistant response.
        """

    @abstractmethod
    async def set_model(self, model: BaseModel) -> None:
        """
        Change the current assistant knowledge model.

        :param model: The assistant model to set.
        """

    @abstractmethod
    async def export_model(self) -> tuple[Any, str]:
        """
        Export the assistant knowledge model asynchronously
        without blocking the assistant invocation.

        :return: A tuple containing the exported model and its
            extension.
        """
